name: Build riscv64

on:
  push:
    branches: [master, feature/build-docker]
  pull_request:
  workflow_dispatch:

jobs:
  build_riscv64:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v5

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            gcc-riscv64-linux-gnu \
            g++-riscv64-linux-gnu

      - name: Build modules
        run: ./build.sh modules riscv64

      - name: Build zisklib
        run: ./build.sh zisklib riscv64

      - name: Build bflat
        run: ./build.sh bflat riscv64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #   - name: Log in to Docker Hub
      #     uses: docker/login-action@v3
      #     with:
      #       username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #       password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push image to Docker Hub
        run: |
          docker build . -t nethermindeth/bflat-riscv64
